### ISSUE TITLE
BE: how to implement versions in our data?

### ISSUE THREAD

**Issue by Nalochen** [Nalochen/jtr-2.0#13]
ACs:
- recherche: wie kann man Versionierung in Projekten für Entitäten umsetzen?
- Was ist die beste Methode für unser Projekt?

**Comment by LeanderCS** [comment]
In einem Versionierungssystem, bei dem nicht alle Felder direkt in der Versions-Tabelle vorhanden sind (z.B. bei `UserVersion`), speichert man typischerweise nur die Änderungen in einem kompakten Format, wie z.B. JSON. Das bedeutet, dass die Versionstabelle nicht jedes Mal den gesamten Zustand des Objekts speichert, sondern nur die Felder, die sich im Vergleich zur vorherigen Version geändert haben.

Hier ist ein Ansatz, wie man das umsetzen könnte:

1. **Änderungen als JSON speichern**: In der Versionstabelle speicherst du nur die geänderten Felder und deren Werte. Der Rest der Daten wird aus der Originaltabelle (`User`) bezogen.
   
2. **Versionen abrufen**: Beim Abrufen von Versionen eines Objekts (z.B. `User`) kombinierst du die Basisdaten mit den Änderungen aus der Versionstabelle, um den Zustand des Objekts zu einem bestimmten Zeitpunkt darzustellen.

### Beispiel für User-Versioning:

#### `UserVersion` Klasse

```python
import json

class UserVersion(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    version = db.Column(db.Integer, nullable=False)
    changes = db.Column(db.Text, nullable=False)  # Änderungen als JSON gespeichert
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)

    # Methoden, um JSON-Daten zu speichern/abzurufen
    def get_changes(self):
        return json.loads(self.changes)

    def set_changes(self, changes_dict):
        self.changes = json.dumps(changes_dict)
```

#### Versionen speichern

Angenommen, ein Benutzer ändert seine `email` und `name`. Du würdest nur diese Änderungen in der Versionstabelle speichern:

```python
# Beispiel: Ein User hat seine Daten geändert
user = User.query.get(1)  # Hole den aktuellen User

# Speichere die Änderungen in der UserVersion Tabelle
changes = {
    "email": "new_email@example.com",
    "name": "New Name"
}

new_version = UserVersion(user_id=user.id, version=2)
new_version.set_changes(changes)
db.session.add(new_version)
db.session.commit()
```

#### Versionen abrufen

Um eine bestimmte Version eines Users abzurufen, würdest du die Basisdaten aus der `User`-Tabelle nehmen und dann die Änderungen aus der `UserVersion` anwenden.

```python
# Hole den aktuellen User
user = User.query.get(1)

# Hole eine bestimmte Version (z.B. Version 2)
version = UserVersion.query.filter_by(user_id=user.id, version=2).first()

# Hole die Änderungen aus dieser Version
changes = version.get_changes()

# Erstelle ein kombiniertes Objekt mit den Änderungen
user_data = {
    "email": user.email,  # Basisdaten
    "name": user.name,
    "birthday": user.birthday
}

# Wende die Änderungen an
for field, value in changes.items():
    user_data[field] = value

# Jetzt enthält `user_data` die Daten der gewünschten Version
print(user_data)
```

#### Vorteile dieses Ansatzes:
1. **Effizienz**: Du speicherst nur die geänderten Felder, anstatt jedes Mal den gesamten Datensatz zu duplizieren.
2. **Flexibilität**: Du kannst jederzeit die aktuelle Version eines Objekts rekonstruieren, indem du die Basisdaten und die Änderungen zusammenführst.
3. **Speicherplatz**: Da nur die geänderten Felder gespeichert werden, wird weniger Speicher benötigt als bei einer vollständigen Versionierung aller Felder.

#### Alternative: Vollständige Versionen speichern
Falls du doch lieber jede Version mit allen Feldern speichern möchtest, könntest du alle Felder aus der Haupttabelle in die Versions-Tabelle kopieren. Allerdings erhöht sich der Speicherverbrauch, und es wird weniger effizient.

Hoffe, das hilft! Lass mich wissen, ob du weitere Fragen dazu hast oder ob ich dir Beispiele für vollständige Versionierung zeigen soll.
