### ISSUE TITLE
BE: add missing data to database and apis

### ISSUE THREAD

**Issue by Nalochen** [Nalochen/jtr-2.0#185]

**Comment by Nalochen** [comment]
Ich brauche im FE folgende Daten:

Table: Tournament:
- arrivalStart: Datum, optional
- arrivalEnd: Datum, optional
- Kosten: Objekt, besteht aus folgenden Daten -> alle Daten sind optional:
  - registrationFee: int,
  - registrationFeePricingType: PricingTypeEnum,
  - deposit: int,
  - depositPricingType: PricingTypeEnum,
  - accommodation: int,
  - accommodationPricingType: PricingTypeEnum,
  - guests: int,
  - guestsPricingType: PricingTypeEnum,
  - additionalText: Freitextfeld,
- Deadlines: Anpassung: Die Deadlines sind einfach ein Freitextfeld, kein Array
- AccommodationType: Anpassung: sollte das Enum AccommodationTypeEnum sein
- tournamentSystem.type brauchen wir nicht, die Spalte kann komplett entfernt werden

Table: User
- pronouns: Freitextfeld (irgendwie 255 Zeichen oder so), optional

Enums:
export enum PricingTypeEnum {
  PER_TEAM = 'PER_TEAM',
  PER_PERSON = 'PER_PERSON',
}
export enum AccommodationTypeEnum {
  CAMPING = 'CAMPING',
  GYM = 'GYM',
  OTHER = 'OTHER',
  NONE = 'NONE',
}

**Comment by LeanderCS** [comment]
Wurde bereits in #30 erledigt
