### ISSUE TITLE
Pflichtenheft schreiben

### ISSUE THREAD

**Issue by Nalochen** [Nalochen/jtr-2.0#60]
Beschreibung der Stand-der-Technik und Motivation
Pflichtenheft

**Comment by Fruchtzwerg08** [comment]
@Nalochen @LeanderCS Bitte das Pflichtenheft einmal nach Rechtschreibung und Richtigkeit überprüfen. 

https://docs.google.com/document/d/17ozj9Bmg5N9jj8uW4fEo-XdlvfiDCp1K/edit?usp=sharing&ouid=118339576060124629308&rtpof=true&sd=true

**Comment by LeanderCS** [comment]
@Fruchtzwerg08 Huch, da warst du aber schnell. 🔥

Ich habe gerade noch kein Zugriff auf das Dokument, habe aber gerade eine Zugriffsanfrage gesendet.

**Comment by Fruchtzwerg08** [comment]
@LeanderCS Ich hab dir den Zugriff gegeben. Sollte jetzt funktionieren : )

**Comment by LeanderCS** [comment]
@Fruchtzwerg08 Bist du dir sicher bei ``` PNF100 ```  ?
Aufgrund von Datenschutz und ein paar anderen Bestimmungen stelle ich mir eine solche Implementierung, beim bereits existierenden Arbeitsumfang, als überproportional aufwendig vor

**Comment by Nalochen** [comment]
Bei PNF130: "Die Aufzeichnungen werden auch im Tugeny Turnierbaum verlinkt. Es kann nach Turnieren oder Teams gefiltert werden." der Satz müsste raus, über Tugeny haben wir keine Kontrolle, das gehört zu anderen Leuten, ansonsten voll gut, danke!!
@LeanderCS PNF100 ist richtig so :)

**Comment by Fruchtzwerg08** [comment]
@LeanderCS @Nalochen ich hab das Pflichtenheft nochmal angepasst und schicke der Dozentin das jetzt um nach Feedback zu fragen :) 
Ich würde vorschlagen für den Meilenstein 2 wieder so vorzugehen wie für den Meilenstein 1: 
Die Übung abwarten, was die von uns will. Das Ding am Wochenende fertigstellen und zu euch in die Review geben, um später noch genügend Zeit zu haben um nach Feedback zu fragen. 
Gebt dem Kommentar einfach einen Daumen hoch oder so, wenn ihr einverstanden seid.

**Comment by Fruchtzwerg08** [comment]
"Hallo Moa,

Ihr seid auf dem richtigen Weg. Ich würde mir die Anforderungen, die ihr unter die Überschrift "Nicht-funktionale Anforderungenen" getan habt noch einmal anschauen und überdenken, ob sie alle wirklich dort hin gehören.

Unter Stand-der-Technik wäre es schön, wenn ihr zu den Screenshots jeweils beschreiben könntet: was ihr verbessern wollt, warum? was ihr übernehmen wollt, warum? Ihr habt einführend einiges beschrieben, aber es könnte systematischer sein. Beim analysieren des Ist-Zustands werdet ihr so langsam auch eine Vision für die neue Webseite und das neue System bekommen.

Viele Grüße,
Burcu"

Ich passe das Pflichtenheft nochmal an :)

**Comment by Karuuna** [comment]
Hab ne Struktur vorgeschlagen und die nichtfunktionalen geschrieben, denke die passen besser. Das was derzeit bei den nichtfunktionalen ist klingt größtenteils noch nach optionalen funktionalen Dingen.

Hab meine Vorschläge der Einfachheit halber direkt ins Dok geschrieben, hoffe das ist okay 👀

**Comment by Nalochen** [comment]
@Fruchtzwerg08 ich finde es sieht auf jeden Fall schon mal gut aus. Du hast jetzt ja immer erst den Text der sich auf ein Bild bezieht und danach das zugehörige Bild. Du könntest das noch tauschen, so dass die Leser*innen erst das Bild sehen und dann sich circa vorstellen können worauf wir uns beziehen. Ansonsten Haken von mir :)

**Comment by Fruchtzwerg08** [comment]
Hab ich nochmal angepasst :)
