### ISSUE TITLE
Fake-Daten erstellen

### ISSUE THREAD

**Issue by Nalochen** [Nalochen/jtr-2.0#65]
Wir brauchen einige Daten, die wir als Test-Daten in unserer Datenbank benutzen können
Hierbei soll eine Datei (CSV oder JSON) erstellt werden, in der Testdaten liegen, die wir in unsere Datenbank einpflegen können (gerne Edge-Cases beachten)
Unser genaues Datenbankmodell ist im PR von #14 hinterlegt

**Comment by LeanderCS** [comment]
Mit #41 existiert eine einfache Möglichkeit, mit 1 Klick eine beliebige Anzahl an Test-Daten in der DB zu erstellen
