### ISSUE TITLE
Meilenstein 3

### ISSUE THREAD

**Issue by Nalochen** [Nalochen/jtr-2.0#73]
Anwendungsfalldiagramme
GUI-Design in Form von Mockups

**Comment by Fruchtzwerg08** [comment]
@Nalochen @LeanderCS bitte schaut noch mal drüber, ob alles stimmt und ob ich was vergessen habe.
![Image](https://github.com/user-attachments/assets/87b64682-3257-4355-8094-60fe390c18dc)

**Comment by Nalochen** [comment]
sieht gut aus, danke!

**Comment by Fruchtzwerg08** [comment]
Hier die neue Version: 
![Image](https://github.com/user-attachments/assets/519d6d80-1897-4c3a-ba60-c0c46b579b23)
